import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import TopNav from "@/app/_components/widgets/topnav";
import Footer from "@/app/_components/widgets/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "AppServices, a list of apps that provide some services.",
  description: "Generated by sovsov###gmail.com",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <TopNav />
        <div className="md:cotainer min-h-120 block max-w-screen-xl md:mx-auto">
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </div>
        <Footer />
      </body>
    </html>
  );
}
